name: Create Release and Tag
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
          
      - name: Create Release and Tag
        run: |
         new_tag=$(TZ=America/Sao_Paulo date +v%d.%m.%Y.%H%M)

          # Crie uma tag
          git tag "$new_tag"

          # Dê permissão de execução ao script
          chmod +x generate-release-notes.sh
          
          # Gere as notas de lançamento
          release_notes=$(./generate-release-notes.sh)

          # Crie um release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "tag_name": "'"$new_tag"'",
              "target_commitish": "master",
              "name": "Release '"$new_tag"'",
              "body": "'"$release_notes"'",
              "draft": false,
              "prerelease": false
            }' \
            "https://api.github.com/repos/${{ github.repository }}/releases"

          # Empurre a tag e as alterações para o repositório remoto
          git push origin "$new_tag"
          git push origin master

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
